export enum EnvKey {
  MODE = 'MODE_API',
  PORT = 'PORT',
  SECURE = 'IS_SECURE',
  DB_CONNECTION_URI = 'MONGO_CONNECTION_URI',
  SIGNATURE_API_KEY = 'SIGNATURE_API_KEY',
  SIGNATURE_SECRET_KEY = 'SIGNATURE_SECRET_KEY',
  JWT_ACCESS_KEY = 'JWT_ACCESS_SECRET',
  JWT_ACCESS_LIMIT = 'JWT_ACCESS_LIMIT',
  JWT_REFRESH_KEY = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_LIMIT = 'JWT_REFRESH_LIMIT',
}
