export const GENERIC_ERROR_CODES = {
  ARGUMENT_INVALID: 'GENERIC.ARGUMENT_INVALID',
  ARGUMENT_OUT_OF_RANGE: 'GENERIC.ARGUMENT_OUT_OF_RANGE',
  ARGUMENT_NOT_PROVIDED: 'GENERIC.ARGUMENT_NOT_PROVIDED',
  UNAUTHORIZED: 'GENERIC.UNAUTHORIZED',
  NOT_FOUND: 'GENERIC.NOT_FOUND',
  CONFLICT: 'GENERIC.CONFLICT',
  INTERNAL: 'GENERIC.INTERNAL_ERROR',
} as const;
